--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sean/Images/wallpaper/1568937803645.png"

-- Special
background="#100a04"
foreground="#dfc8a5"
cursor="#dfc8a5"

-- Colors
color0="#100a04"
color1="#9A6C2C"
color2="#926A30" -- regular
color3="#C07F1D" -- saturated
color4="#9B7847" -- light
color5="#B78739" -- darker light
color6="#B48A4C" -- light
color7="#dfc8a5"
color8="#9c8c73"
color9="#9A6C2C"
color10="#926A30"
color11="#C07F1D"
color12="#9B7847"
color13="#B78739"
color14="#B48A4C"
color15="#dfc8a5"
