--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module XMonad.Colors.Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sean/Images/wallpaper/wallhaven-472036.jpg"

-- Special
background="#007C80"
foreground="#dfeded"
cursor="#dfeded"

-- Colors
color0="#007C80"
color1="#8da1a1"
color2="#94a7a8"
color3="#98aaaa"
color4="#a8b7b7"
color5="#bbc7c7"
color6="#c6d0d0"
color7="#dfeded"
color8="#9ca5a5"
color9="#8da1a1"
color10="#94a7a8"
color11="#98aaaa"
color12="#a8b7b7"
color13="#bbc7c7"
color14="#c6d0d0"
color15="#dfeded"
