--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module XMonad.Colors.Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sean/Images/wallpaper/wallhaven-301875.jpg"

-- Special
background="#190f0b"
foreground="#b4b4b9"
cursor="#b4b4b9"

-- Colors
color0="#190f0b"
color1="#884519"
color2="#89441B"
color3="#8A542C"
color4="#9B6537"
color5="#9B704E"
color6="#AB8767"
color7="#b4b4b9"
color8="#7d7d81"
color9="#884519"
color10="#89441B"
color11="#8A542C"
color12="#9B6537"
color13="#9B704E"
color14="#AB8767"
color15="#b4b4b9"

