# Define o raio das bordas (ajuste ao seu gosto)
corner-radius = 10;

# Evita arredondar janelas específicas (opcional)
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# Opcional: Adicione um leve blur e sombra para combinar
shadow = false;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;

# Opacidade das janelas ATIVAS (focadas) - 1.0 é totalmente sólido
active-opacity = 1.0;

# Opacidade das janelas INATIVAS (fora de destaque)
# 0.8 significa 80% de opacidade. Ajuste conforme seu gosto.
inactive-opacity = 0.95;
frame-opacity = 1.0;

# Garante que a opacidade inativa não se aplique a janelas que 
# tecnicamente estão "ativas", como menus de contexto.
inactive-opacity-override = true;

# focus-exclude = [
#     "class_g = 'Cairo-clock'",
#     "class_g = 'slop'",                    # Para ferramentas de screenshot
#     "class_g = 'XTerm'",                   # Exemplo se quiser uma exceção
#     "name *?= 'xmobar'",                   # Mantém a barra sólida
#     "_NET_WM_WINDOW_TYPE *= '_NET_WM_WINDOW_TYPE_DESKTOP'", # Wallpaper
#     "_NET_WM_WINDOW_NAME = 'xfce4-panel'"
# ];

fading = false;
fade-delta = 4;        # Velocidade da transição (em ms)
fade-in-step = 0.03;   # Opacidade ganha por passo ao focar
fade-out-step = 0.03;  # Opacidade perdida ao desfoca
# Use o backend glx para suportar shaders
backend = "glx";

# Evita que janelas fiquem transparentes por erro de foco


window-shader-fg-rules = [
    "/home/arch/.config/picom/shaders/glasses.glsl:window_type = 'desktop'",
    "/home/arch/.config/picom/shaders/glasses.glsl:class_g = 'feh'"
];



