* init

#+BEGIN_SRC emacs-lisp :results none
(require 'use-package)
(unless (package-installed-p 'use-package)
;;  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-verbose t)
(setq use-package-always-ensure t)

(use-package auto-compile
  :config (auto-compile-on-load-mode))
(setq load-prefer-newer t)

(setq desktop-load-locked-desktop t)

(add-to-list 'load-path "~/.emacs.d/lisp/")

#+END_SRC

** server mode

#+BEGIN_SRC emacs-lisp
;;(server-start)
(if (and (fboundp 'server-running-p)
 		 (not (server-running-p)))
 	(server-start)
 1)
#+END_SRC

** CANCELADO conserta o teclado
essas funções são para o teclado do meu notebook que está com algumas
teclas quebradas. Arrumei com o xmodmap. Vou deixar isso aqui caso dê
algum problema nele

#+begin_src emacs-lisp
;; (define-key key-translation-map (kbd "<f1>") (kbd "TAB"))
;; (define-key key-translation-map (kbd "<f2>") (kbd "("))
;; (define-key key-translation-map (kbd "<f5>") (kbd "+"))
;; (define-key key-translation-map (kbd "<f6>") (kbd "-"))
;; (define-key key-translation-map (kbd "<f7>") (kbd "="))
;; (define-key key-translation-map (kbd "<f8>") (kbd "_"))
;; (define-key key-translation-map (kbd "<f9>") (kbd "õ"))
;; (define-key key-translation-map (kbd "<f11>") (kbd "ã"))
;; (define-key key-translation-map (kbd "<C-f1>") (kbd "1"))
;; (define-key key-translation-map (kbd "<C-f2>") (kbd "2"))
;; (define-key key-translation-map (kbd "<C-f3>") (kbd "3"))
;; (define-key key-translation-map (kbd "<C-f4>") (kbd "4"))
;; (define-key key-translation-map (kbd "<C-f5>") (kbd "5"))
;; (define-key key-translation-map (kbd "<C-f6>") (kbd "6"))
;; (define-key key-translation-map (kbd "<C-f7>") (kbd "7"))
;; (define-key key-translation-map (kbd "<C-f8>") (kbd "8"))
;; (define-key key-translation-map (kbd "<C-f9>") (kbd "9"))
#+end_src


** exec path

#+begin_src emacs-lisp
(setenv "PATH" (concat (getenv "PATH") ":~/.local/bin"))
(setq exec-path (append exec-path '("~/.local/bin")))
#+END_SRC

* repositórios

#+BEGIN_SRC emacs-lisp
(unless (assoc-default "melpa" package-archives)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t))
(unless (assoc-default "org" package-archives)
  (add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t))
#+END_SRC

* acentos

#+BEGIN_SRC emacs-lisp
(require 'iso-transl)
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
#+END_SRC

* aparência
** ewal

#+begin_src emacs-lisp
(use-package ewal
  :init (setq ewal-use-built-in-always-p nil
              ewal-use-built-in-on-failure-p nil
              ewal-built-in-palette "sexy-material"))
#+end_src

** texto

#+begin_src emacs-lisp
;; highlight lines
(global-hl-line-mode)
#+end_src

** barra de rolagem, menu e modeline. scroll step

#+begin_src emacs-lisp
(scroll-bar-mode -1)
(setq scroll-step            1
      scroll-conservatively  10000)
(tool-bar-mode -1)
(menu-bar-mode -1)
#+end_src

** ESPERANDO modeline
linha que coloca o relógio na modeline preciso confirmar depois
#+begin_src emacs-lisp
(setq-default mode-line-buffer-identification (list -40 (propertized-buffer-identification "%12b")))
#+end_src

** pretty printing

#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode 1)
#+END_SRC

* configurações
  
** autosave
coloca os autosaves numa pasta só ao invés de largar junto com os arquivos
#+begin_src emacs-lisp
(defvar user-temporary-file-directory "~/.emacs-autosaves/")
(make-directory user-temporary-file-directory t)
(setq backup-by-copying t)
(setq backup-directory-alist `(("." . ,user-temporary-file-directory) 
			       (tramp-file-name-regexp nil)))
(setq auto-save-list-file-prefix (concat user-temporary-file-directory ".auto-saves-"))
(setq auto-save-file-name-transforms `((".*" ,user-temporary-file-directory t)))
#+end_src

* extensões adicionais
** PRA FAZER [#B] pdf tools 
montar um esquema dentro do emacs pra tirar pedaços de imagens de pdfs
#+BEGIN_SRC emacs-lisp
(add-hook 'pdf-view-mode-hook (lambda () (linum-mode -1)))
(use-package pdf-view-restore)
(add-hook 'pdf-view-mode-hook (lambda () (pdf-view-restore-mode t)))
(use-package pdfgrep)
(use-package pdf-tools
  :ensure t
  ;; :pin manual ;; manually update
  :config
  ;; initialise
  (pdf-tools-install)
  ;; numero de páginas no cache. default 64
  (setq pdf-cache-image-limit 15)
  ;; tempo que ele demora pra apagar uma imagem do cache
  (setq image-cache-eviction-delay 180)
  ;; open pdfs scaled to fit page
  ;; fit-height, fit-width, fit-page
  (setq-default pdf-view-display-size 'fit-page)
  ;; automatically annotate highlights
  (setq pdf-annot-activate-created-annotations t)
  ;; 
  ;; use normal isearch
  ;; (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)
  ;; turn off cua so copy works
  (add-hook 'pdf-view-mode-hook (lambda () (cua-mode 0)))
  ;; more fine-grained zooming
  (setq pdf-view-resize-factor 1.1)
  ;; keyboard shortcuts
  (define-key pdf-view-mode-map (kbd "h") 'pdf-annot-add-highlight-markup-annotation)
  (define-key pdf-view-mode-map (kbd "t") 'pdf-annot-add-text-annotation)
  (define-key pdf-view-mode-map (kbd "D") 'pdf-annot-delete)
  (define-key pdf-view-mode-map (kbd "z") 'org-noter))

;; troca a cor do midnight mode para combinar com a cor do tema
(setq pdf-view-midnight-colors (cons (face-attribute 'default :foreground) (face-attribute 'default :background)))
#+END_SRC

*** PRA FAZER [#C] extensão para estimar o tempo
terminar esse troço e colocar num arquivo separado. Tá horrível isso
largado aqui.

preciso ver isso depois. Talvez pensar melhor na abordagem
#+begin_src
;; TODO FAZER O BÁSICO PRIMEIRO
(setq pdf-time-before 0)
(setq pdf-time-after 0)
;; TODO adicionar uma função para chamar isso
(add-hook 'pdf-view-after-change-page-hook (lambda () (progn (set-pdf-time-after)
														(message (int-to-string (- pdf-time-after pdf-time-before)))
														(set-pdf-time-before))))

(defun set-pdf-time-after ()
  (setq pdf-time-after (hhmmtomm (car (split-string (substring-no-properties display-time-string) " ")))))

(defun set-pdf-time-before ()
  (setq pdf-time-before (hhmmtomm (car (split-string (substring-no-properties display-time-string) " ")))))

;; TODO uma função que checa se avançamos nas páginas
(defun pdf-check-page-advance ()
  (interactive)
  "checks if we are going forward on non-read pages"
  (if (not (member (pdf-view-current-page) pdf-time-pages))
	  (setq pdf-time-pages (append (pdf-view-current-page)))))
;; TODO uma função que conta o tempo numa página
;; TODO uma outra função que estima o tempo final
;; TODO uma função que pega a última página como algo arbitrário para remover índices no final
#+end_src

*** PRA FAZER [#C] testes pdf1
não sei o que é isso
#+begin_src emacs-lisp
;; (defun org-noter-insert-selected-text-inside-note-content ()
;;   (interactive)
;;   (progn (setq currenb (buffer-name))
;; 		 (org-noter-insert-precise-note)
;; 		 (set-buffer currenb)
;; 		 (org-noter-insert-note)))


;; (define-key pdf-view-mode-map (kbd "y") 'org-noter-insert-selected-text-inside-note-content)
#+end_src

** PRA FAZER [#A] flyspell
transformar isso num hook do flyspell mode e colocar algumas outras
keys úteis
#+begin_src emacs-lisp
  ;; (define-key flyspell-mode-map (kbd "C-,") #'flyspell-goto-next-error)
#+end_src

** try

#+BEGIN_SRC emacs-lisp
(use-package try)
#+END_SRC


** rainbow mode 
visualizar cores no buffer
#+begin_src emacs-lisp
(use-package rainbow-mode)
#+end_src

** nov mode (epub)

#+BEGIN_SRC emacs-lisp
(use-package nov)
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))

(defun my-nov-font-setup ()
  (face-remap-add-relative 'variable-pitch :family "Liberation Serif"
                                           :height 1.0))
(add-hook 'nov-mode-hook 'my-nov-font-setup)
(add-hook 'nov-mode-hook 'visual-line-mode)
;; justification on buffers
(load "justify-kp")
;; (use-package justify-kp)
(setq nov-text-width t)

(defun my-nov-window-configuration-change-hook ()
  (my-nov-post-html-render-hook)
  (remove-hook 'window-configuration-change-hook
               'my-nov-window-configuration-change-hook
               t))

(defun my-nov-post-html-render-hook ()
  (if (get-buffer-window)
      (let ((max-width (pj-line-width))
            buffer-read-only)
        (save-excursion
          (goto-char (point-min))
          (while (not (eobp))
            (when (not (looking-at "^[[:space:]]*$"))
              (goto-char (line-end-position))
              (when (> (shr-pixel-column) max-width)
                (goto-char (line-beginning-position))
                (pj-justify)))
            (forward-line 1))))
    (add-hook 'window-configuration-change-hook
              'my-nov-window-configuration-change-hook
              nil t)))

(add-hook 'nov-post-html-render-hook 'my-nov-post-html-render-hook)
;;(add-hook 'nov-mode-hook 'visual-fill-column-mode)
#+END_SRC


** smart parens

#+BEGIN_SRC emacs-lisp
(use-package smartparens
  :hook (prog-mode . smartparens-mode)
  :config
  (global-set-key (kbd "C-<right>") 'sp-forward-slurp-sexp)
  (global-set-key (kbd "C-<left>") 'sp-forward-barf-sexp)
  (global-set-key (kbd "C-M-<left>") 'sp-backward-slurp-sexp)
  (global-set-key (kbd "C-M-<right>") 'sp-backward-barf-sexp))
#+END_SRC

** leet code

#+BEGIN_SRC emacs-lisp
(use-package leetcode)
(setq leetcode-prefer-language "python3")
(setq leetcode-prefer-sql "mysql")
#+END_SRC

** zettelkasten
*** deft
#+begin_src emacs-lisp
(use-package deft
  :commands deft
  :init
  (setq deft-default-extension "org"
        ;; de-couples filename and note title:
        deft-use-filename-as-title nil
        deft-use-filter-string-for-filename t
        ;; disable auto-save
        deft-auto-save-interval -1.0
        ;; converts the filter string into a readable file-name using kebab-case:
        deft-file-naming-rules
        '((noslash . "-")
          (nospace . "-")
          (case-fn . downcase)))
  :config
  (add-to-list 'deft-extensions "tex")
  )
#+end_src


*** diretórios
#+begin_src emacs-lisp
  (setq
   org_notes "/ubuntu/home/sean/" ;; (concat (getenv "HOME") "/Git/Gitlab/Mine/Notes/")
   zot_bib (concat (getenv "HOME") "/Minha biblioteca.bib")
   org-directory org_notes
   deft-directory org_notes
   org-roam-directory org_notes)
#+end_src

*** PRA FAZER org roam
isso daqui tá uma bagunça e muito grande. preciso organizar e dividir
em blocos menores
#+begin_src emacs-lisp

  (use-package org-roam
    :hook (org-load . org-roam-mode)
    :commands (org-roam-buffer-toggle-display
               org-roam-find-file
               org-roam-graph
               org-roam-insert
               org-roam-switch-to-buffer
               org-roam-dailies-date
               org-roam-dailies-today
               org-roam-dailies-tomorrow
               org-roam-dailies-yesterday)
    :preface
    ;; Set this to nil so we can later detect whether the user has set a custom
    ;; directory for it, and default to `org-directory' if they haven't.
    ;; (defvar org-roam-directory nil)
    :init
    :config
    (add-to-list 'org-roam-capture-templates
                 '("w" "webref" plain (function org-roam-capture--get-point)
                   "%?"
                   :file-name "web/${slug}"
                   :head "#+TITLE: ${title}\n#+ROAM_KEY: %x\n#+ROAM_ALIAS: \n#+ROAM_TAGS: ${tags} \n#+CREATED: %u\n#+LAST_MODIFIED: %U\n- links :: \n\n"
                   :unnarrowed t))
    (add-to-list 'org-roam-capture-templates '("r" "regular" plain (function org-roam-capture--get-point)
                                               "%?"
                                               :file-name "${slug}"
                                               :head "#+TITLE: ${title}\n#+ROAM_KEY: \n#+ROAM_ALIAS: \n#+ROAM_TAGS: ${tags} \n#+CREATED: %u\n#+LAST_MODIFIED: %U\n- links :: \n\n"
                                               :unnarrowed t))
    (require 'org-roam-protocol)
    (setq 
  ;; org-roam-directory (expand-file-name (or org-roam-directory "roam")
  ;;                                               org-directory)
          org-roam-verbose nil  ;; https://youtu.be/fn4jIlFwuLU
  ;; changed this 
          ;; org-roam-buffer-no-delete-other-windows t ;; make org-roam buffer sticky
                  org-roam-buffer-window-parameters '((no-delete-other-windows . t))
          org-roam-completion-system 'default
                  org-roam-graph-executable "/usr/bin/dot"
                  org-roam-graph-viewer "/usr/bin/google-chrome-stable"
                  org-roam-completion-system 'helm
                  org-roam-index-file "index.org"


    ;; Normally, the org-roam buffer doesn't open until you explicitly call
    ;; `org-roam'. If `+org-roam-open-buffer-on-find-file' is non-nil, the
    ;; org-roam buffer will be opened for you when you use `org-roam-find-file'
    ;; (but not `find-file', to limit the scope of this behavior).
    ;; (add-hook 'find-file-hook
    ;;   (defun +org-roam-open-buffer-maybe-h ()
    ;;     (and +org-roam-open-buffer-on-find-file
    ;;          (memq 'org-roam-buffer--update-maybe post-command-hook)
    ;;          (not (window-parameter nil 'window-side)) ;; don't proc for popups
    ;;          (not (eq 'visible (org-roam-buffer--visibility)))
    ;;          (with-current-buffer (window-buffer)
    ;;            (org-roam-buffer--get-create)))))

    ;; ;; Hide the 
    ;; mode line in the org-roam buffer, since it serves no purpose. This
    ;; makes it easier to distinguish among other org buffers.
    ;; (add-hook 'org-roam-buffer-prepare-hook #'hide-mode-line-mode)
                  )
    :bind (:map org-roam-mode-map
                            (("C-c n l" . org-roam)
                             ("C-c n f" . org-roam-find-file)
                             ("C-c n g" . org-roam-graph)
                             ("C-c n i" . org-roam-insert)
                             ("C-c n I" . org-roam-insert-immediate)
                             ("C-c n d" . deft)))
    )


  ;; Since the org module lazy loads org-protocol (waits until an org URL is
  ;; detected), we can safely chain `org-roam-protocol' to it.

  ;; (use-package org-roam-protocol
  ;;   :after org-protocol)



#+end_src

**** org-roam-bibtex
#+begin_src emacs-lisp
  (use-package org-roam-bibtex
    :after org-roam
    :hook (org-roam-mode . org-roam-bibtex-mode)
    :config

    (setq orb-preformat-keywords
     '("=key=" "title" "url" "file" "author-or-editor" "keywords"))

    (setq orb-templates
	  '(("r" "ref" plain (function org-roam-capture--get-point)
	     ""
	     :file-name "${slug}"
	     :head "#+TITLE: ${=key=}: ${title}\n#+ROAM_KEY: ${ref}
	     - tags ::
	     - keywords :: ${keywords}
	     \n* ${title}\n  :PROPERTIES:\n  :Custom_ID: ${=key=}\n  :URL: ${url}\n  :AUTHOR: ${author-or-editor}\n  :NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n  :NOTER_PAGE: \n  :END:\n\n"
	     :unnarrowed t))))
#+end_src

** relative linum

#+BEGIN_SRC emacs-lisp
(use-package linum-relative)
(column-number-mode 1)
(setq linum-relative-current-symbol "")
#+END_SRC


** rainbow delimiters

#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters)
#+END_SRC

** anki
https://yiufung.net/post/anki-org/
- By default anki-editor-cloze-{dwim,region} always asks for hints and
  requires card number input. I don’t use hints much, and usually want
  card number to increase, so two helper functions
  anki-editor-cloze-region-{auto-incr,dont-incr} are written to skip
  these behaviors. (Note: Such kind of customizations are ubiquitous
  in Emacs community, where users don’t have to wait for upstream to
  implement a desired new feature. This is quite different from Anki
  community where version updates frequently break existing add-ons,
  leaving end-users hands tied, or new features being delayed due to
  technical difficulty in understanding the code base.)

- A function is added to org-capture-after-finalize-hook to reset
  cloze number to 1 after each capture

- By default anki-editor-push-notes will push the whole file. This is
  slow when the file contain old entries that didn’t really need to
  change. In my workflow, I keep all pending notes under Dispatch
  Shelf subtree, and push that whole subtree (with <f9>) when I feel
  ready. Once they’re pushed, I would refile/relocate them under
  Exported subtree. anki-editor-push-tree is added for this purpose.

- Assign handy keybindings (<f9>-<f12> in this case) to your liking.
#+begin_src emacs-lisp
(use-package anki-editor
  :after org
  :bind (:map org-mode-map
              ("<f12>" . anki-editor-cloze-region-auto-incr)
              ("<f11>" . anki-editor-cloze-region-dont-incr)
              ("<f10>" . anki-editor-reset-cloze-number)
              ("<f9>"  . anki-editor-push-tree))
  :hook (org-capture-after-finalize . anki-editor-reset-cloze-number) ; Reset cloze-number after each capture.
  :config
  (setq anki-editor-create-decks t ;; Allow anki-editor to create a new deck if it doesn't exist
        anki-editor-org-tags-as-anki-tags t)

  (defun anki-editor-cloze-region-auto-incr (&optional arg)
    "Cloze region without hint and increase card number."
    (interactive)
    (anki-editor-cloze-region my-anki-editor-cloze-number "")
    (setq my-anki-editor-cloze-number (1+ my-anki-editor-cloze-number))
    (forward-sexp))
  (defun anki-editor-cloze-region-dont-incr (&optional arg)
    "Cloze region without hint using the previous card number."
    (interactive)
    (anki-editor-cloze-region (1- my-anki-editor-cloze-number) "")
    (forward-sexp))
  (defun anki-editor-reset-cloze-number (&optional arg)
    "Reset cloze number to ARG or 1"
    (interactive)
    (setq my-anki-editor-cloze-number (or arg 1)))
  (defun anki-editor-push-tree ()
    "Push all notes under a tree."
    (interactive)
    (anki-editor-push-notes '(4))
    (anki-editor-reset-cloze-number))
  ;; Initialize
  (anki-editor-reset-cloze-number)
  )
#+end_src



#+begin_src emacs-lisp
(setq org-my-anki-file "/ubuntu/home/sean/anki.org")

;; Allow Emacs to access content from clipboard.
(setq select-enable-clipboard t
      select-enable-primary t)
#+end_src


** PRA FAZER screencast gif / keycast
arrumar o keycast
ver como que mexe nisso e montar um notes e fazer um post 
#+BEGIN_SRC emacs-lisp
(use-package gif-screencast)
(use-package keycast)
;;(setq keycast-insert-after "%e")
(with-eval-after-load 'gif-screencast
  (define-key gif-screencast-mode-map (kbd "<f8>") 'gif-screencast-toggle-pause)
  (define-key gif-screencast-mode-map (kbd "<f9>") 'gif-screencast-stop))
;;(setq mode-line-format mode-line-keycast)
#+END_SRC

** undo tree

#+BEGIN_SRC emacs-lisp
(use-package undo-tree)
(global-undo-tree-mode)
#+END_SRC

* interface
** frames only
esse daqui só presta se for pra usar os frames separados. Tipo no
Qtile, i3, xmonad e etc.

#+BEGIN_SRC emacs-lisp
(use-package frames-only-mode)
(frames-only-mode 1)
#+END_SRC

** yes or no para y or n

#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** multiterm

#+begin_src emacs-lisp
(use-package multi-term)
(setq multi-term-program "/bin/bash")
#+end_src

** which key

#+BEGIN_SRC emacs-lisp
(use-package which-key)
(which-key-mode 1)
;; (setq which-key-popup-type 'minibuffer)
(setq which-key-popup-type 'side-window)
(setq which-key-side-window-max-height 0.33)
#+END_SRC

** PRA FAZER helm
ver esse negócio e dividir em partes
#+BEGIN_SRC emacs-lisp
(use-package helm-bibtex
  :custom
  (bibtex-completion-bibliography '("/home/sean/Minha biblioteca.bib"))
  (reftex-default-bibliography '("//home/sean/Minha biblioteca.bib"))
  (bibtex-completion-notes-path "/ubuntu/home/sean/")
  (bibtex-completion-pdf-field "file")
  (bibtex-completion-notes-template-multiple-files
  (concat
   "#+TITLE: ${title}\n"
   "#+ROAM_KEY: cite:${=key=}\n"
   "* TODO Notes\n"
   ":PROPERTIES:\n"
   ":Custom_ID: ${=key=}\n"
   ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
   ":AUTHOR: ${author-abbrev}\n"
   ":JOURNAL: ${journaltitle}\n"
   ":DATE: ${date}\n"
   ":YEAR: ${year}\n"
   ":DOI: ${doi}\n"
   ":URL: ${url}\n"
   ":END:\n\n"
   ))
)
(use-package helm
  :diminish helm-mode
  :init
  (progn
    (require 'helm-config)
    (setq helm-candidate-number-limit 100)
    ;; From https://gist.github.com/antifuchs/9238468
    (setq helm-idle-delay 0.0 ; update fast sources immediately (doesn't).
          helm-input-idle-delay 0.01  ; this actually updates things
                                        ; reeeelatively quickly.
          helm-yas-display-key-on-candidate t
		  ;; changed this
		  ;; helm-completion-in-region-fuzzy-match t
		  helm-completion-style 'emacs
		  helm-ff-auto-update-initial-value t
		  helm-split-window-inside-p t
          helm-quick-update t
		  ;; helm-mode-fuzzy-match t
          helm-M-x-requires-pattern nil
          helm-ff-skip-boring-files t)
    (helm-mode))
  :bind (("C-c h" . helm-mini)
         ("C-h a" . helm-apropos)
         ("C-x C-b" . helm-buffers-list)
         ("C-x b" . helm-buffers-list)
         ("M-y" . helm-show-kill-ring)
         ("M-x" . helm-M-x)
         ("C-x c o" . helm-occur)
         ("C-x c s" . helm-swoop)
         ("C-x c y" . helm-yas-complete)
         ("C-x c Y" . helm-yas-create-snippet-on-region)
         ("C-x c b" . my/helm-do-grep-book-notes)
         ("C-x c SPC" . helm-all-mark-rings)))

(ido-mode -1) ;; Turn off ido mode in case I enabled it accidentally
#+END_SRC



*** pacotes adicionais helm

#+begin_src emacs-lisp
(use-package helm-swoop)
(use-package helm-c-yasnippet)
(use-package helm-org-rifle)
#+end_src

*** PRA FAZER atalhos do teclado
arrumar isso e colocar junto com outros atalhos
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-s") 'helm-occur)
#+END_SRC

** hydra

#+begin_src emacs-lisp
(use-package hydra)
#+end_src

** PRA FAZER god mode
não está funcionando
#+begin_src emacs-lisp
(use-package god-mode
  :config
  (define-key god-local-mode-map (kbd "i") 'god-local-mode)
  (global-set-key (kbd "<escape>") 'god-local-mode))

(god-mode-all)

(defun my-update-cursor ()
  (setq cursor-type (if (or god-local-mode buffer-read-only)
                        'box
                      'bar)))

(add-hook 'god-mode-enabled-hook 'my-update-cursor)
(add-hook 'god-mode-disabled-hook 'my-update-cursor)
#+end_src



** PRA FAZER espeak
fazer ele não abrir essa janela
não lembro pra quê eu montei isso mas dá pra usar em alguma coisa
#+BEGIN_SRC emacs-lisp
;; depende do espeak
(defun espeak (text)
  "Speaks text by espeak"
  (save-window-excursion
    (let* ((amplitude 100)
           (voice 'brazil)
           (command (format "espeak -a %s -v %s \"%s\"" amplitude voice text)))
      (async-shell-command command "*Messages*" "*Messages*"))))
#+END_SRC

** PRA FAZER desktop save
não tem necessidade de deixar isso aqui
#+BEGIN_SRC emacs-lisp
(desktop-save-mode 1)
#+END_SRC

** PRA FAZER key binds
juntar com as outras keybinds
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC

* Org mode
** PRA FAZER Módulos adicionais
separar isso daqui em vários blocos

#+BEGIN_SRC emacs-lisp
(setq org-enable-org-journal-support t)
(add-to-list 'org-modules 'org-tempo t)
;; não sei porque mas os módulos do org-plus-contrib precisam ser usados com require
(require 'org-habit)
(require 'org-tempo)
;; TODO este pedaço não está funcionando
(setq org-startup-folded 'content) ;; default t)
(use-package org-journal
  :bind
  ("C-c n j" . org-journal-new-entry))

(use-package org-pretty-tags)
(use-package org-ref
    :config
    (setq
         org-ref-completion-library 'org-ref-ivy-cite
         org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex
         org-ref-default-bibliography (list "/home/sean/Minha biblioteca.bib")
         org-ref-bibliography-notes "/ubuntu/home/sean/biblio.org"
         org-ref-note-title-format "* PRA FAZER %y - %t\n :PROPERTIES:\n  :Custom_ID: %k\n  :NOTER_DOCUMENT: %F\n :ROAM_KEY: cite:%k\n  :AUTHOR: %9a\n  :JOURNAL: %j\n  :YEAR: %y\n  :VOLUME: %v\n  :PAGES: %p\n  :DOI: %D\n  :URL: %U\n :END:\n\n"
         org-ref-notes-directory "/ubuntu/home/sean/"
         org-ref-notes-function 'orb-edit-notes))

(use-package org-download
  :custom
  (org-download-screenshot-method "gnome-screenshot")
  (org-download-image-dir "./assets/images"))
(use-package html-to-markdown)

(use-package auto-org-md)
(setq org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
(setq plantuml-default-exec-mode 'jar)
#+END_SRC

** PRA FAZER org-noter
https://orgmode.org/manual/Initial-visibility.html
olhar isso daqui e mexer nas coisas do org mode depois
também preciso ver um jeito de montar um 'smartcast' pra selecionar as
caixas do slice
#+BEGIN_SRC emacs-lisp
(use-package org-noter
  :config
  (setq org-noter-auto-save-last-location t
		org-noter-notes-window-behavior '(start scroll)
		org-noter-hide-other nil
		;; abrir em outra janela
		org-noter-notes-window-location 'other-frame
		;; org-noter-notes-window-location 'horizontal-split
		org-noter-separate-notes-from-heading t)

  (defun org-noter-init-pdf-view ()
	(pdf-view-fit-page-to-window))
;;	(pdf-view-auto-slice-minor-mode)
	;; (run-at-time "0.5 sec" nil #'org-noter))

  (add-hook 'pdf-view-mode-hook 'org-noter-init-pdf-view))
  
(defun org-noter-insert-pdf-slice-note (event &optional switch-back)
  (interactive "@e")
  (setq current-b (buffer-name))
  (progn  (pdf-view-mouse-set-region-rectangle event)
		  (pdf-view-extract-region-image pdf-view-active-region
										 (pdf-view-current-page)
										 (pdf-view-image-size)
										 (get-buffer-create "teste")
										 t)
		  (set-buffer "teste")
		  (write-file "/tmp/screenshot.png" nil)
		  (kill-buffer "screenshot.png")
		  (set-buffer current-b)
		  (org-noter-insert-note)
		  (org-download-screenshot)
		  (if switch-back			 
			  (switch-to-buffer-other-frame current-b))))

(define-key pdf-view-mode-map [C-M-down-mouse-1] 'org-noter-insert-pdf-slice-note)
#+END_SRC

** PRA FAZER org-agenda
vou testar aquele C-c [ de adicionar os arquivos pra agenda e ver no
que dá. Pelo menos vai dar uma limpada nela
#+BEGIN_SRC emacs-lisp
;; TODO colocar os arquivos direitinho nesse negócio
(setq org-agenda-files '("~/.emacs.d/config.org"))
;;                         "/ubuntu/home/sean"
;;						 "/ubuntu/home/sean/web"))

(global-set-key (kbd "C-c a") 'org-agenda)
#+END_SRC

** org aparência

#+BEGIN_SRC emacs-lisp
(setq org-startup-indented t
	  org-ellipsis "";; " ⤵" ;; folding symbol
      org-pretty-entities t
      org-hide-emphasis-markers nil       ;; show actually italicized text instead of /italicized text/
      org-agenda-block-separator ""
      org-fontify-whole-heading-line t
      org-fontify-done-headline t
      org-fontify-quote-and-verse-blocks t
      org-special-ctrl-a/e t)
#+END_SRC

** org pomodoro
#+BEGIN_SRC emacs-lisp
(use-package org-pomodoro)
;; duração
(setq org-pomodoro-length 50)
;; duração dos intervalos curtos
(setq org-pomodoro-short-break-length 10)
;;duração dos intervalos longos
(setq org-pomodoro-long-break-length 20)
;; frequência dos intervalos longos
(setq org-pomodoro-long-break-frequency 3)

(setq org-pomodoro-audio-player "mplayer")

(setq org-pomodoro-finished-sound-args "-volume 0.4")
(setq org-pomodoro-long-break-sound-args "-volume 0.4")
(setq org-pomodoro-short-break-sound-args "-volume 0.4")
#+END_SRC

** PRA FAZER [#C] org clock 
depois ver isso com calma
#+BEGIN_SRC emacs-lisp
;; acho que não tem necessidade de usar essa função
(defun hhmmtomm (time)
  "converts hh:mm formated time string to minutes int"
  (if time
   (if (= 4 (length time))
	   (+ (* (string-to-number (substring time 0 1)) 60)
		  (string-to-number (substring time 2)))
	   (+ (* (string-to-number (substring time 0 2)) 60)
		  (string-to-number (substring time 3))))
   0))

(defun speak-current-task ()
  "function that says the name out loud"
  (espeak org-clock-current-task))

(display-time)
(defun esf/org-clocking-info-to-file ()
  (with-temp-file "/tmp/clocking"
    ;; (message (org-clock-get-clock-string))
    (if (org-clock-is-active)
        (insert (format "\ue003 %s: %d (%d->%d) min %d cd"
						org-clock-heading
                        (- (org-clock-get-clocked-time) org-clock-total-time)
                        org-clock-total-time
                        (org-clock-get-clocked-time)  ;; all time total
						;; FIX ME fazer isso usando funções nativas do emacs lisp
						(- (hhmmtomm org-clock-effort)
						   (- (org-clock-get-clocked-time)
							  org-clock-total-time))))))) ;;(org-clock-get-clock-string)
(esf/org-clocking-info-to-file)
(add-hook 'org-clock-in 'esf/org-clocking-info-to-file)
(add-hook 'org-clock-in-prepare-hook 'esf/org-clocking-info-to-file)
(add-hook 'display-time-hook 'esf/org-clocking-info-to-file)
#+END_SRC

** interface

#+begin_src emacs-lisp
(setq org-use-speed-commands 1)
#+end_src

*** org refile

#+begin_src emacs-lisp
;; org refiling pra mandar as tarefas de um arquivo pra outro
(setq org-refile-targets (quote (;;("~/semana.org" :maxlevel . 1)
								 ;;("~/notes_accomplished.org" :maxlevel . 1)
								 ;;("~/vest/vestibular.org" :maxlevel . 1)
								 ;; ("~/done.org" :maxlevel . 1) 
								 ;; ("~/ossu/ossu.org" :maxlevel . 1)
								 ("/ubuntu/home/sean/anki.org" :maxlevel . 1))))
#+end_src

*** PRA FAZER org capture
adicionar mais templates e consertar o de imagens
#+BEGIN_SRC emacs-lisp
(setq org-capture-templates
      '(;;		Org-capture anki templates
		("j" "Japanese basic"
		 entry
		 (file+headline org-my-anki-file "Dispatch Shelf")
		 "* %<%H:%M:%S>   :japones:\n :PROPERTIES:\n :ANKI_NOTE_TYPE: Japanese (recognition&recall)\n :ANKI_DECK: japones\n :END:\n** Expression\n%x\n** Meaning\n%?\n** Reading\n%x\n** Kanji\n\n** Diagram\n\n** Imagem \n\n** Audio \n\n** ref\n\n")
		;; TODO adicionar um outro pra francês, alemão e russo
		("c" "Cloze"
		 entry
		 (file+headline org-my-anki-file "Dispatch Shelf")
		 "* %<%H:%M:%S>   %^g\n:PROPERTIES:\n:ANKI_NOTE_TYPE: Cloze\n:ANKI_DECK: Mega\n:END:\n** Text\n%x%?\n** Extra\n")
		("a" "Anki cloze"
		 entry
		 (file+headline org-my-anki-file "Dispatch Shelf")
		 "* %<%H:%M:%S>   %^g\n:PROPERTIES:\n:ANKI_NOTE_TYPE: Cloze\n:ANKI_DECK: Mega\n:END:\n** Text\n%x\n** Extra\n")
		;; TODO não está funcionando
		("i" "Image cloze"
		 entry
		 (file+headline org-my-anki-file "Dispatch shelf")
		 "* %<%H:%M:%S>   %^g\n:PROPERTIES:\n:ANKI_NOTE_TYPE: Image\n:ANKI_DECK: Mega\n:END:\n** Descrição\n%?\n** Imagem\n\n** Comentários\n")))

(global-set-key (kbd "C-c c") 'org-capture)
#+END_SRC

**** anki comments

- Note the %x in org-capture-templates: this means we want to fill in
  content of X clipboard upon capture. For Cloze note, this would be
  in Text field. For Basic note, I usually like to put them in Back,
  and come up with a good question for Front field.

- The key to be as lazy as possible is to let Emacs not only read
  explicitly copied/paste content (via C-c / C-v, the CLIPBOARD
  selection), but also the currently selected text (the PRIMARY
  selection). That way, after highlighting text with mouse I can
  immediately call org-capture (C-c c) in Emacs. See Clipboard -
  ArchWiki for details.

- Header name does not really matter in anki-editor, %H:%M is an
  arbitrary choice

- I put most notes in a Mega deck following Michael Nielson’s advice
  (Search “Use one big deck”). It served me well. If you have many
  decks/note types, you may want to create multiple capture templates,
  or write some elisp functions to reduce typing.

*** hooks

#+begin_src emacs-lisp
(add-hook 'org-mode-hook (lambda () (auto-fill-mode 1)))
(setq org-startup-with-inline-images t)
(add-hook
 'org-babel-after-execute-hook
 (lambda ()
   (when org-inline-image-overlays
     (org-redisplay-inline-images))))
#+end_src

*** todo states

#+begin_src emacs-lisp
;; todo states
(setq org-todo-keywords '((sequence "PRA FAZER(t)" "ESPERANDO(e)" "NÃO ENTENDI(n)" "REVER(r)" "|" "PRONTO(p)" "CANCELADO(c)")))
#+end_src

** org babel

#+BEGIN_SRC emacs-lisp
(use-package ob-sml)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((clojure    . t)
   (dot        . t)
   (shell      . t)
   (C          . t)
   ;;(cpp        . t)
   (sml        . t)
   (haskell    . t)
   (scheme     . t)
   (sml        . t)
   (python     . t)
   (ocaml      . t)
   (restclient . t)
   (emacs-lisp . t)
   (plantuml   . t)
   (js         . t)
   (octave     . t)
   (R          . t)
   (ruby       . t)))

(setq org-confirm-babel-evaluate nil
      org-src-fontify-natively t
      org-src-tab-acts-natively t
	  org-src-preserve-indentation nil
	  org-edit-src-content-indentation 0)
#+END_SRC

** ox exports
#+begin_src emacs-lisp
(use-package ox-jekyll-md)
(use-package ox-epub)
(use-package ox-reveal)
#+end_src

** PRA FAZER org publish jekyll
#+begin_src emacs-lisp
(setq org-publish-project-alist
      '(("seanvert.github.io"
         ;; Path to org files.
         :base-directory "~/ossu/org"
         :base-extension "org"

         ;; Path to Jekyll Posts
         :publishing-directory "~/Desktop/projetos/seanvert.github.io/_posts"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :html-extension "html"
         :body-only t
         )))
#+end_src

* programming
** hooks

#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook (lambda () (progn (linum-relative-mode 1)
									   (smartparens-mode 1)
									   (rainbow-delimiters-mode 1))))
#+END_SRC
** realgud
#+begin_src emacs-lisp
(use-package realgud)
#+end_src

** PRA FAZER lsp
depois preciso ver isso com mais calma, acho que vale a pena
configurar pra clojure e pra python. Haskell acho que vai ocupar muito
espaço no disco.
#+begin_src emacs-lisp
(use-package lsp-ui
  :ensure t
  :requires lsp-mode flycheck
  :commands lsp-ui-mode
  :config
  (setq lsp-ui-doc-enable t
		lsp-ui-doc-use-childframe t
		lsp-ui-doc-position 'top
		lsp-ui-doc-include-signature t
		lsp-ui-sideline-enable nil
		lsp-ui-flycheck-enable t
		lsp-ui-flycheck-list-position 'right
		lsp-ui-flycheck-live-reporting t
		lsp-ui-peek-enable t
		lsp-ui-peek-list-width 60
		lsp-ui-peek-peek-height 25))



(use-package lsp-treemacs
  :commands lsp-treemacs-errors-list)
(use-package helm-lsp
  :after helm
  :commands helm-lsp-workspace-symbol
  :config
  (defun netrom/helm-lsp-workspace-symbol-at-point ()
	(interactive)
    (let ((current-prefix-arg t))
      (call-interactively #'helm-lsp-workspace-symbol)))
  
  (defun netrom/helm-lsp-global-workspace-symbol-at-point ()
    (interactive)
    (let ((current-prefix-arg t))
      (call-interactively #'helm-lsp-global-workspace-symbol))))


(use-package dap-mode)
(setq dap-auto-configure-features '(sessions locals controls tooltip))
(use-package lsp-python-ms)
;;(use-package lsp-clangd)

(use-package lsp-mode
  :requires hydra helm helm-lsp
  :commands (lsp lsp-deferred)
  :hook (haskell-mode . lsp)
  :config
(setq lsp-diagnostic-package nil
;; changed this 
;; lsp-prefer-flymake nil
		netrom--general-lsp-hydra-heads
        '(;; Xref
          ("d" xref-find-definitions "Definitions" :column "Xref")
          ("D" xref-find-definitions-other-window "-> other win")
          ("r" xref-find-references "References")
          ("s" netrom/helm-lsp-workspace-symbol-at-point "Helm search")
          ("S" netrom/helm-lsp-global-workspace-symbol-at-point "Helm global search")

          ;; Peek
          ("C-d" lsp-ui-peek-find-definitions "Definitions" :column "Peek")
          ("C-r" lsp-ui-peek-find-references "References")
          ("C-i" lsp-ui-peek-find-implementation "Implementation")

          ;; LSP
          ("p" lsp-describe-thing-at-point "Describe at point" :column "LSP")
          ("C-a" lsp-execute-code-action "Execute code action")
          ("R" lsp-rename "Rename")
          ("t" lsp-goto-type-definition "Type definition")
          ("i" lsp-goto-implementation "Implementation")
          ("f" helm-imenu "Filter funcs/classes (Helm)")
          ("C-c" lsp-describe-session "Describe session")

          ;; Flycheck
          ("l" lsp-ui-flycheck-list "List errs/warns/notes" :column "Flycheck"))

        netrom--misc-lsp-hydra-heads
        '(;; Misc
          ("q" nil "Cancel" :column "Misc")
          ("b" pop-tag-mark "Back")))
   ;; Create general hydra.
   (eval `(defhydra netrom/lsp-hydra (:color blue :hint nil)
			,@(append
			   netrom--general-lsp-hydra-heads
			   netrom--misc-lsp-hydra-heads)))

  (add-hook 'lsp-mode-hook
            (lambda () (local-set-key (kbd "C-c C-l") 'netrom/lsp-hydra/body))))
#+end_src

** markdown
#+begin_src emacs-lisp
(use-package 
  markdown-mode 
  :commands (markdown-mode gfm-mode)
  ;; github flavor markdown
  :mode (("README\\.md\\'" . gfm-mode) 
	 ("\\.md\\'" . markdown-mode) 
	 ("\\.markdown\\'" . markdown-mode)) 
  :init (setq markdown-command "multimarkdown"))
#+end_src

** flycheck

#+BEGIN_SRC emacs-lisp
(use-package flycheck)
  ;; :ensure t)
  ;; :init
  ;; (add-hook 'prog-mode-hook 'flycheck-mode))
  ;;(global-flycheck-mode t))
(use-package flycheck-irony)
(use-package flycheck-haskell)
(use-package flycheck-pycheckers)
(use-package flycheck-plantuml)
(use-package flycheck-cask)
#+END_SRC

** magit git

#+BEGIN_SRC emacs-lisp
(use-package magit)
#+END_SRC

** PRA FAZER company
depois preciso ver o company 
#+BEGIN_SRC emacs-lisp
(use-package company
  :ensure t
  :config
  (add-hook 'prog-mode-hook 'company-mode)
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 1))

;; global company mode
(add-hook 'after-init-hook 'global-company-mode)

(setq company-dabbrev-other-buffers t)

(use-package company-math)

;; (use-package company-box
;;   :hook (company-mode . company-box-mode)
;;   :config
;;   (setq company-box-doc-delay 0.3)
;;   (setq company-box-enable-icon nil)
;;   (setq company-box-color-icon nil))

(eval-after-load 'company
  '(define-key company-active-map (kbd "C-n") #'company-select-next-or-abort))
(eval-after-load 'company
  '(define-key company-active-map (kbd "C-p") #'company-select-previous-or-abort))
#+END_SRC



*** company colors
#+begin_src emacs-lisp
(let ((bg (face-attribute 'default :background)))
    (custom-set-faces
     `(company-tooltip ((t (:inherit default :background ,bg))))
     `(company-scrollbar-bg ((t (:background ,(color-lighten-name bg 10)))))
     `(company-scrollbar-fg ((t (:background ,(color-lighten-name bg 5)))))
     `(company-tooltip-selection ((t (:inherit font-lock-function-name-face))))
     `(company-tooltip-common ((t (:inherit font-lock-constant-face))))))
#+end_src

*** company backends

**** company-org-roam
#+begin_src emacs-lisp
(use-package company-org-roam
  :requires company
  :after org-roam
  :config
(push 'company-org-roam company-backends)
)


  ;; (set-company-backend! 'org-mode '(company-org-roam company-yasnippet company-dabbrev))
#+end_src

** outros parametros

*** tamanho das tabulações

#+BEGIN_SRC emacs-lisp
(setq-default tab-width 4)
#+END_SRC


** web

#+begin_src emacs-lisp
(use-package skewer-mode)
(use-package emmet-mode
:ensure t
:defer t
:mode ("\\.html\\'"
	   "\\.css\\'"
	   "\\.ejs\\'"))

(unless (package-installed-p 'indium)
  (use-package indium))
(setq indium-chrome-executable "google-chrome-stable")

(use-package json-mode
:ensure t
:defer t)
(use-package typescript-mode
:ensure t
:defer t)
(use-package js2-mode
:mode ("\\.js\\'" . js2-mode)
:ensure t
:defer t)
(use-package web-mode
:ensure t
:defer t
:mode ("\\.html\\'"
 ;; "\\.css\\'"
 "\\.php\\'"
 "\\.ejs\\'"))

(setq web-mode-enable-current-column-highlight t
	  web-mode-enable-current-element-highlight t)
(add-hook 'web-mode-hook 'emmet-mode)
(setq emmet-move-cursor-between-quotes t)

(add-hook 'web-mode-before-auto-complete-hooks
    '(lambda ()
     (let ((web-mode-cur-language
  	    (web-mode-language-at-pos)))
               (if (string= web-mode-cur-language "php")
    	   (yas-activate-extra-mode 'php-mode)
      	 (yas-deactivate-extra-mode 'php-mode))
               (if (string= web-mode-cur-language "css")
    	   (setq emmet-use-css-transform t)
      	 (setq emmet-use-css-transform nil)))))

#+end_src



*** PRA FAZER javascript prettier
#+begin_src emacs-lisp
;; (setq company-tooltip-align-annotations t)

;; (setq flycheck-javascript-standard-executable "/home/sean/.npm-global/bin/standardx")
;; (use-package prettier-js)

;; (add-hook 'js-mode-hook #'setup-tide-mode)
(add-hook 'js-mode-hook 'prettier-js-mode)

(setq prettier-js-args '(
  "--trailing-comma" "none"
  "--bracket-spacing" "true"
  "--single-quote" "true"
  "--no-semi" "true"
  "--jsx-single-quote" "true"
  "--jsx-bracket-same-line" "true"
  "--print-width" "100"))
#+end_src

*** rest client
#+begin_src emacs-lisp
(use-package restclient)
(use-package ob-restclient)
#+end_src
** yasnippets

#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :config
  (defun mars/company-backend-with-yas (backends)
      "Add :with company-yasnippet to company BACKENDS.
Taken from https://github.com/syl20bnr/spacemacs/pull/179."
      (if (and (listp backends) (memq 'company-yasnippet backends))
	  backends
	(append (if (consp backends)
		    backends
		  (list backends))
		'(:with company-yasnippet))))
    ;; add yasnippet to all backends
  (setq company-backends
		(mapcar #'mars/company-backend-with-yas company-backends))
  (yas-global-mode 1))

(use-package auto-yasnippet
  :config
  (global-set-key (kbd "C-,") #'aya-create)
  (global-set-key (kbd "C-.") #'aya-expand))

(use-package yasnippet-snippets
  :config
  (setq yas-snippet-dirs '("/home/sean/.emacs.d/snippets"
						   yasnippet-snippets-dir)))

#+END_SRC

** projectile

#+BEGIN_SRC emacs-lisp
(use-package projectile
  :config
  (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))
(setq projectile-use-git-grep t)
#+END_SRC

** helm dash

#+BEGIN_SRC emacs-lisp
(use-package helm-dash
  :config
   (setq helm-dash-common-docsets '("Python_3" "Standard ML"))
   (setq helm-dash-browser-func 'browse-url))
#+END_SRC

** rust
#+begin_src emacs-lisp
(use-package rust-mode)
(use-package rustic)
#+end_src

** octave

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.m" . octave-mode))
#+END_SRC

** C

#+BEGIN_SRC emacs-lisp
(use-package company-irony)
#+END_SRC

** python

#+BEGIN_SRC emacs-lisp
(add-hook 'python-mode-hook
		  (lambda () (setq tab-width 4
					  python-indent-offset 4)))
#+END_SRC



*** django
#+begin_src emacs-lisp
(use-package django-mode)
;; (yas/load-directory "/home/sean/.emacs.d/elpa/django-mode-20170522.714/snippets")
;; (add-to-list 'auto-mode-alist '("\\.djhtml$" . django-html-mode))
#+end_src

** haskell

#+BEGIN_SRC emacs-lisp
(use-package haskell-snippets)
(use-package company-ghci)
(use-package lsp-haskell
  :ensure t
  :config
  (setq lsp-haskell-process-path-hie "ghcide")
  (setq lsp-haskell-process-args-hie '()))
#+END_SRC

** lisp

#+begin_src emacs-lisp
(show-paren-mode 1)
(setq show-paren-style 'parenthesis)
#+end_src

** yaml
#+begin_src emacs-lisp 
(use-package yaml-mode
  :config
  (add-to-list 'auto-mode-alist '("\\.yml\\'" . yaml-mode))
  (add-hook 'yaml-mode-hook
			'(lambda ()
			   (define-key yaml-mode-map "\C-m" 'newline-and-indent))))
#+end_src

** sml

#+BEGIN_SRC emacs-lisp
(use-package sml-mode)
#+END_SRC


** PRA FAZER howdoyou stackoverflow consult
montar um negócio pra enfiar no capture

#+BEGIN_SRC emacs-lisp
(use-package howdoyou)

(with-eval-after-load "helm-net"
  (push (cons "How Do You"  (lambda (candidate) (howdoyou-query candidate)))
        helm-google-suggest-actions))
#+END_SRC

* properties
#+PROPERTY: header-args    :results silent
